- name: create node_exporter user group
  group: name="{{groupId}}"
  become: true

- name: create node_exporter user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes # makes it a system account rather than a human user
    shell: "/sbin/nologin" # makes a user not able to login
    createhome: "no" # do not create a home directory
    state: present

- name: Download node_exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: true # download on the target nodes and not the ansible hub

- name: Copying the binaries from tmp to bin
  copy:
    src: "/tmp/node_exporter-{{version}}-linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755
    remote_src: yes

- name: Deleting the tmp folder
  file:
    path: "/tmp/node_exporter-{{version}}-linux-amd64"
    state: absent

- name: Copying systemd init file
  template: # copy module can't handle the variables in the .j2 file so we use template module
    src: "exporter.service.j2"
    dest: "/etc/systemd/system/{{serviceName}}.service"
  notify: systemd_reload # calls the handler

- name: Start node_exporter service
  service:
    name: "{{serviceName}}"
    state: started
    enabled: yes

- name: Check if node_exporter is working
  uri:
    url: http://localhost:9100/metrics
    method: GET
    status_code: 200
