---
- name: Setup AlertManager
  hosts: name_alertmanager
  become: true
  roles:
    - alertmanager

- name: Setup Node Exporter
  hosts: name_node_exporter
  become: true
  roles:
    - node_exporter

- name: Setup Prometheus
  hosts: name_prometheus
  become: true
  roles:
    - prometheus

- name: Setup Grafana
  hosts: name_grafana
  become: true
  roles:
    - grafana
